# Generated by Django 3.0.3 on 2020-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='id',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='branches',
            name='bank_id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
