# Generated by Django 3.0.3 on 2020-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20200217_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='bank_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='ifsc',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
