# Generated by Django 3.0.3 on 2020-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200217_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='bank_name',
            field=models.CharField(default='', max_length=49),
        ),
    ]
