# Generated by Django 3.0.3 on 2020-02-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20200217_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='bank_name',
            field=models.CharField(default='', max_length=149),
        ),
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.CharField(max_length=150),
        ),
    ]
