# Generated by Django 3.0.3 on 2020-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20200218_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ifsc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(default='0')),
                ('branch', models.CharField(max_length=74)),
                ('address', models.CharField(max_length=195)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=26)),
                ('bank_name', models.CharField(default='', max_length=149)),
            ],
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
